# Generated by Django 4.2 on 2023-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("placa", models.CharField(max_length=50)),
            ],
        ),
    ]
