# Generated by Django 4.2 on 2023-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
