# Generated by Django 4.2 on 2023-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_carro_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
