# Generated by Django 4.2 on 2023-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_carro_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="media/uploads"),
        ),
    ]
