# Generated by Django 4.2 on 2023-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_carro_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
