# Generated by Django 4.2 on 2023-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_carro_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(blank="True", upload_to="image")),
            ],
        ),
    ]
