# Generated by Django 4.2 on 2023-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_teste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(
                blank=True,
                upload_to="C:\\Users\\Luis Felipe\\Documents\\GitHub\\CRUD_com_Python_Webdesign_em_Foco\\media",
            ),
        ),
    ]
