# Generated by Django 4.2 on 2023-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_carro_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="uploads"),
        ),
    ]
