# Generated by Django 4.2 on 2023-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_carro_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="imagem",
            field=models.ImageField(
                blank=True, default="./media/image/padraoCarro.jpg", upload_to="uploads"
            ),
        ),
    ]
